### ISSUE TITLE
Reuniao para conhecer os membros do grupo

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2020-1-Ziguen#1]
Dia X as 8 hrs tem reuniao pro grupo de se conhecer na plataforma Y..

- Falar habilidade

**Comment by RochaCarla** [comment]
Todo muito foi na reuniao, e nos conhecemos

**Comment by edsondearaujo** [comment]
Tivemos uma reunião dia 21/08 às 20 hrs  para o grupo se alinhar, definir papeis e sentir a motivação de cada um. A reunião aconteceu de forma online na plataforma Jitsi.

- [x] Conhecemos um pouco da habilidade de cada um

- [x] Discutimos sobre as propostas de temas 

- [x]  Definimos funções de cada membro

Critério de aceitação:

- [x] Todos os integrantes estavam presentes na reunião

**Comment by gabrielapivetta** [comment]
![Screenshot from 2020-08-21 20-08-37](https://user-images.githubusercontent.com/65376200/90961686-ad203900-e478-11ea-98e4-1083bc8ee72f.png)
Foto da nossa reunião para a primeira Sprint!
