### ISSUE TITLE
Estudo Tecnológico

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#10]
Pesquisar, estudar e entender quais tecnologias iremos usar no projeto

# Tarefas

- [x] Tipo de Tecnologia
- [x] Trajetória Tecnológica
- [x] Capacidade Tecnológica 

# Critério de Aceitação

- [x] Tecnologia Estabilizada
- [x]  Pesquisa revisada

**Comment by edsondearaujo** [comment]
Após fazer uma breve análise de algumas tecnologias, avaliar o conhecimento prévio da equipe, considerar o que vai atender nossas expectativas com relação ao projeto, optamos por trabalhar com as seguintes tecnologias:

**Tecnologias para front-end:**
- BOOTSTRAP 
- CSS e Media Queries
- JS
- HTML

**Tecnologias para back-end:**
- Node
- Sqlite3 (Banco de dados) 
- Dependências: express
- Para instalação: yarn ou npm. (configurações)
 
**Tecnologias para DevOps:**
- C++ (opcional)
- Docker
- Docker-compose
- Travis-CI
- JUnit
- Python

**Comment by edsondearaujo** [comment]
#74
