### ISSUE TITLE
Planejamento de Comunicação

### ISSUE THREAD

**Issue by liversonp** [fga-eps-mds/2020-1-Ziguen#11]
Entender o que é preciso resolver e organizar como vai funcionar a comunicação

### **Tarefas**

- [x] Formação de objetivo e metas;

- [x] Estabelecer um cronograma;

- [x] Estabelecer orientação criativa;

- [x] Desenvolvimento de estratégias de comunicação e ferramentas;

- [x] Capacitar equipe;

- [x] Pensar a longo prazo;

- [x] Avaliar, adaptar e melhorar.

### **Critérios de Aceitação**

- [x] Planejamento revisado;

- [x] Tarefas realizadas.

**Comment by francisco1code** [comment]
Planejamento revisado durante uma breve reunião no jit.si com @edsondearaujo @francisco1code @liversonp

**Comment by edsondearaujo** [comment]
Acho que devemos aderir a dica do Victor e centralizar nossa comunicação aqui no repositório. Dailys e assuntos urgentes, podemos manter no Telegram
