### ISSUE TITLE
Deploy da API Ziguen

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#115]
**Descrição**
- Fazer Deploy no heroku

**Tarefas** 
   - [x] Fazer o deploy com docker no heroku

**Critérios de aceitação**
- [x] A api do ziguen está em ambiente de homologação

**Comment by edsondearaujo** [comment]
### Referências:

- [Deployando seu app no Heroku com o Dropbox](https://www.youtube.com/watch?v=ZAGLhteVM-M&feature=emb_title&ab_channel=CodePrestige)
- [Heroku e NodeJS](https://www.heroku.com/nodejs)
- [ Preparando uma base de código para implantação do Heroku](https://devcenter.heroku.com/articles/preparing-a-codebase-for-heroku-deployment)
