### ISSUE TITLE
Visualizar projetos de semestres anteriores

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#12]
Conhecer padrão da organização de repositórios de grupos da matéria MDS de semestres anteriores.

> Coloque abaixo sua sugestão de projeto
Utilize a formatação: - [ nome do projeto ](link do repositório)

**Sugestão:** 
- [Breakdown](https://github.com/fga-eps-mds/2019.2-Git-Breakdown)
- [Gymnasteg](https://github.com/fga-eps-mds/2019.2-Gymnasteg-Wiki/tree/master/docs)
- [Acacia-Frontend]( https://github.com/fga-eps-mds/2019.2-Acacia-Frontend )
- [Gerencia_mais ](https://github.com/fga-eps-mds/2018.1_Gerencia_mais.git)
- [Unbreak](https://github.com/fga-eps-mds/2019.1-unbrake)

**Aceitação**
- [x] Todos os membros da equipe sugeriu um projeto

**Comment by edsondearaujo** [comment]
Essa issue foi criada na intenção de familiarizar a equipe com modelos de documentação adotados por grupos de semestres anteriores, integrar membros da equipe na prática de github, para isso é preciso que todos contribuam fazendo **uma** sugestão de projeto.

**Comment by francisco1code** [comment]
Minha sugestão é o  projeto [Gymnasteg](https://github.com/fga-eps-mds/2019.2-Gymnasteg-Wiki/tree/master/docs), achei bem eficiente a forma de documentação deles.

**Comment by GeiseSaunier** [comment]
Galera, gostei do projeto  - [ 2019.2-Acacia-Frontend ] ( https://github.com/fga-eps-mds/2019.2-Acacia-Frontend ). Ele está bem estruturado e o padrão de desenvolvimento deles é bem acessível. Acho que vale a pena a gente discutir sobre em uma próxima sprint.

**Comment by Giuulob89** [comment]
Gente, eu gostei demais desse repositório aqui: https://github.com/fga-eps-mds/2018.1_Gerencia_mais.git
Além do Read.me estar super organizado e bem feito, a ideia do projeto é muito parecida com a de um dos temas que pensamos para nosso trabalho (prontuário eletrônico) e acho que pode ajudar bastante nesse desenvolvimento.

**Comment by Giuulob89** [comment]
Esse é outro muito interessante e pode ajudar demais, caso escolhamos o tema do prontuário: https://github.com/fga-eps-mds/2017.2-Receita-Mais.git

**Comment by liversonp** [comment]
achei esse repositório bem informacional e encontrei muita coisa relacionado à comunicação e organização do time em relação ao projeto, também havendo alguns programas que não só gameficam, mas também incentivam o time a continuar trabalhando.
https://github.com/fga-eps-mds/2019.1-unbrake

**Comment by gabrielapivetta** [comment]
Gostei muito do Projeto [Gerencia Mais](https://github.com/fga-eps-mds/2018.1_Gerencia_mais). A ideia do projeto, assim como a documentação e o ReadMe foram muito bem elaborados.

**Comment by edsondearaujo** [comment]
#74
