### ISSUE TITLE
Teste Unitarios Admin

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#128]
**Descrição**
- Escrever testes unitarios para o usuario Administrador
   
**Tarefas** 
   - [x] Criar administrador
   - [x] Logar com administrador
   - [x] Altera dados com administrador
   - [x] Listar dados com administrador
   - [x] Exluir com administrador

**Comment by edsondearaujo** [comment]
Para ajudar a contextualizar e registrar o que ando estudando sobre testes, vou deixar aqui algumas referências. 

### Referências:
[Jest - Iniciando com testes e TDD](https://www.youtube.com/watch?v=sLx00kXPoTg&ab_channel=MatheusCastiglioni)
