### ISSUE TITLE
request-font e back

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#131]
**Descrição**
- request-font e back
   
**Tarefas** 
   - [x] Ultilizar a API rest no front-end
   - [x] Pegar dados no banco de dados
   - [x] inserir dados no banco

**Comment by gabrielapivetta** [comment]
Estamos usando esses links para entendermos melhor os Forms de Login e Cadastro e fazermos o request para o back
https://www.youtube.com/watch?v=P65RJTTqkN4&t=2272s
https://github.com/Rocketseat/unform
