### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#16]
# Issues
| nome | assunto| titulo| label | assignees |
|------|------|------|------|-----|
| Issue | Template | Issue tempalte | issue| @francisco1code  | 

### Descrição 
Templates para ser utilizados na criação de novas issue.

[Novo Modelo issue](https://github.com/fga-eps-mds/2020-1--Grupo-1/blob/develop/docs/templates/issue_template/issue_template.md)

# Commits
Verificar as políticas de *commit* em
[Commit](https://github.com/fga-eps-mds/2020-1--Grupo-1/blob/develop/docs/templates/commit_template/commit_policy.md)

# Pull-request
Verificar o template em
[Pull-request](https://github.com/fga-eps-mds/2020-1--Grupo-1/blob/develop/docs/templates/pull_request_template/pull_request_template.md)

###  Criterio de aceitação
- [x] Todos os membros vizualizar os novo formato.

**Comment by GeiseSaunier** [comment]
Compreendi. Precisamos criar um template para os commits.

**Comment by edsondearaujo** [comment]
Criei a política de [commits](https://github.com/fga-eps-mds/2020-1--Grupo-1/blob/develop/docs/templates/commit_template/commit_policy.md)

**Comment by GeiseSaunier** [comment]
Eu criei a última issue e esqueci de seguir o template que combinamos, mas nas próximas farei. Vamos todos tentar seguir o padrão.
