### ISSUE TITLE
Documentação do projeto

### ISSUE THREAD

**Issue by GeiseSaunier** [fga-eps-mds/2020-1-Ziguen#18]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Revisar documentação | Definir funcionalidades | documentation | @GeiseSaunier    | 0.1 |
| Release 1  | Lista de entregas para a release 1 | documentation | @edsondearaujo   | 0.2 |

## Descrição
Visualizar tarefas concluídas

## Tarefas 
- [x] Revisar documentação do projeto e definir quais funcionalidades serão implementadas nesse primeiro momento
#### Release 1 - Entrega 08/10 
- [x] Documento de Visão do Projeto
- [x] Planejamento/Comunicação Interna e Externa (agenda de trabalho + ferramentas), Documento de Arquitetura do Projeto
- [x] Especificação das historias de usuários (critérios de aceitação)
- [x] Configuração do repositório de acordo com os padrões de comunidade de software livre (Github)
- [x] Wiki atualizada
- [x] Protótipo de alta fidelidade

## Critério de aceitação

- [x] Conclusão das tarefas

- [x] Desenvolver pelo menos uma funcionalidade até a release 1

**Comment by GeiseSaunier** [comment]
Gente, se vocês puderem ler a documentação e anotar o que precisa ser melhorado, ajudaria bastante,

**Comment by GeiseSaunier** [comment]
Agora que já escolhemos o ator principal e as funcionalidades, podemos focar nessa parte.

**Comment by GeiseSaunier** [comment]
Anotem para a nossa próxima reunião, aí fazemos as alterações.

**Comment by francisco1code** [comment]
OK, vou fazer mais uma leitura da Documentação.

**Comment by GeiseSaunier** [comment]
Perfeito, Francisco. Anota os pontos relevantes referentes as funcionalidades que vamos implementar, pra dar uma visão geral sobre elas.

**Comment by Giuulob89** [comment]
Ok, farei a leitura e levo as alteracoes na próxima reunião!

**Comment by gabrielapivetta** [comment]
Atualizamos a documentação ontem e subimos para o repositório!

**Comment by edsondearaujo** [comment]
Reabri a issue para possibilitar o time ter uma visão geral das entregas.
Tirei as tarefas da release 1 do cronograma da disciplina.
