### ISSUE TITLE
Treinamento de Docker

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#19]
# Docker

| Apredendo docker | assunto| titulo| label | assignees |
|------|------|------|------|-----|
| Material Docker | Docker e Docker-Compose |Docker  |Docker/Docker-Compose | @francisco1code  | 

## Descrição
*  Docker e Docker-Compose
   - 1- Instalação
    - 2-  Imagem e Conteiner (Hello world no docker)
    - 3- Orquestramento de containers (Aplicação no projeto)
## Material
   - [x] Material disponivel ([Instalação](https://github.com/francisco1code/docs/blob/master/Docker-e-Docker-compose.md))
   - [x] Material disponivel  ([Imagem e conteiner](https://github.com/francisco1code/docs/blob/master/Docker-Imagen_e_Conteiner.md))
   - [x] Material disponivel  ([Orquestramento de containers](https://github.com/francisco1code/docs/blob/master/docker-compose.md))

## Tarefa 

   - [x] Estudar todo material disponível

**Comment by francisco1code** [comment]
# Como Instalar o Docker

 [Issue Referente](#19)
## Primeiro atualize seus pacotes

        sudo apt update

## Permitem que o apt utilize pacotes via HTTPS:

	sudo apt install apt-transport-https ca-certificates curl software-properties-common

## Adicione a chave GPG
	
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -


## Adicione o repositório do Docker

	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

## Atualize seus pacotes novamente (update)
        sudo apt update

## Certifique-se de que você irá instalar a partir do repositório do Docker
	
	apt-cache policy docker-ce

## Instale o Docker
	sudo apt install docker-ce

## Verificação final

	sudo systemctl status docker


## Configuração do docker – adicionar seu usuario ao grupo docker

	sudo usermod -aG docker ${USER}
	
	su - ${USER}
	
	id -nG
	sudo usermod -aG docker nome-do-usuário

## Instalando o docker-compose 


        sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose


## Definir as permissões

	sudo chmod +x /usr/local/bin/docker-compose

## Verificando a versão
	docker-compose --version

**Comment by edsondearaujo** [comment]
Docker e Docker-Compose instalados aqui

**Comment by liversonp** [comment]
Aqui também, instalados com sucesso.

**Comment by Giuulob89** [comment]
Instalado!!

**Comment by francisco1code** [comment]
Galera nesse treinamento de docker eu abordei apenas o necessario para a aplicação em nosso projeto, mais informações é só me procurar, tem um parte de configuração que eu não abordei, fica para um proxima, a sim, todo o material está Disponivel.

**Comment by francisco1code** [comment]
Na parte do docker-compose também não passei como configurar, como já falei o principal intuito é mostra como iremos usar no projeto principalmente quem vai ficar no back-end, é que basicamente 2 comandos. qualquer coisa é só me procurar.

**Comment by francisco1code** [comment]
> Docker e Docker-Compose instalados aqui

Opa isso aí!

**Comment by GeiseSaunier** [comment]
Docker instalado, galera! Dei uma estudada no geral também.

**Comment by gabrielapivetta** [comment]
Reuni com o Francisco, porque tive alguns problemas com a instalação do Docker. Resolvemos e ele já me ensinou os comandos básicos, vou seguir estudando e pesquisando sobre!
