### ISSUE TITLE
Proposta de tema para o projeto de MDS: ZIGUEN!

### ISSUE THREAD

**Issue by GeiseSaunier** [fga-eps-mds/2020-1-Ziguen#2]
**Problema:** Venda de passagens fluviais de forma manual.
**Solução:** Ziguen. A ferramenta trata-se de uma aplicação mobile e plataforma web onde as pessoas poderão adquirir passagens fluviais sem sair de casa, podendo conferir disponibilidade, horários e formas de pagamento com alguns cliques.

**Link para escopo do projeto:** https://drive.google.com/file/d/1szSDWPDAoLFDO-NsZ7RCNJRbm0dTQ6sH/view?usp=sharing

**Comment by RochaCarla** [comment]
nao dá pra fazer no ciclo da disciplina fazer mobile + web.. sugestão: pensar em fazer web responsivo.. até a próxima aula dou um feedback sobre o tema..

**Comment by GeiseSaunier** [comment]
Perfeito, professora. Muito obrigada!

Em ter., 18 de ago. de 2020 às 18:27, Carla Rocha <notifications@github.com>
escreveu:
