### ISSUE TITLE
Estudo e Criação de Diagramas UML

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2020-1-Ziguen#20]
| Título| Assunto | Label | Assignees |
|------|------|------|-----|
| Diagramas UML | Elaboração de Diagramas | documentation / Diagrama_Uml | @gabrielapivetta |

# Descrição
Estudo e elaboração de alguns dos diagramas UML.

# Tarefas 

- [x]  Pesquisar sobre os Diagramas

- [x]  Escolher templates

- [x]  Diagrama de Casos de Uso (@Giuulob89 e @liversonp)

- [x]  Diagrama de Entidade e Relacionamento (@edsondearaujo e @francisco1code)

**Comment by francisco1code** [comment]
[Play List](https://www.youtube.com/watch?v=W2Z1STnjNJo&list=PLucm8g_ezqNoNHU8tjVeHmRGBFnjDIlxD&index=4) sobre MER/DER

**Comment by edsondearaujo** [comment]
@francisco1code dar uma olhada nessa [aula](https://www.youtube.com/watch?v=oPlXecD-gZM&t=501s&ab_channel=UNIVESP). Aí mostra uns pontos que a gente discutiu sobre o MER.

**Comment by edsondearaujo** [comment]
Subi um arquivo jpg do Diagrame de Entidade e Relacionamento dentro da pasta [diagramas](https://github.com/fga-eps-mds/2020-1-Ziguen/tree/develop/docs/diagramas) em docs.

**Comment by francisco1code** [comment]
Foi também criado o Modelo de Entidade e Relacionamento

**Comment by Giuulob89** [comment]
Diagrama de Casos de Uso feito!

**Comment by gabrielapivetta** [comment]
Decidimos que os diagramas que temos até então já são suficientes para iniciarmos a implementação e faremos outros conforme o desenvolvimento do projeto e se surgir a necessidade.
