### ISSUE TITLE
Documento de Arquitetura

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#23]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Documento de Arquitetura | Arquitetura do Projeto | Documentação_de_Arquitetura | @francisco1code  @liversonp   | 2.0 |

# Descrição
Escrever a [Documentação de Arquitetura do Projeto Ziguen](https://github.com/fga-eps-mds/2020-1-Ziguen/blob/develop/docs/wiki/Documento_arquitetura.md)

# Tarefas 

- [ ] Escrever o Documento de Arquitetura

**Comment by francisco1code** [comment]
Uma boa parte da Documentção já foi feita, o restante que falta precisa do diagrama de visão para concluir a issue

**Comment by francisco1code** [comment]
@edsondearaujo  @gabrielapivetta  @GeiseSaunier  @Giuulob89, quem puder dar uma revisada na documentão de arquitetura.

**Comment by Giuulob89** [comment]
@francisco1code @liversonp fui clicar no alí em documentação de arquitetura do projeto ziguen e o github me encaminhou para uma página não encontrada

**Comment by liversonp** [comment]
opa, resolvi aqui, da uma olhada se foi ai certinho. A gnt tinha linkado errado mesmo
