### ISSUE TITLE
Tecnologias

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#26]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Tecnologias | Mudança de Tecnologias | tecnologia | @francisco1code  | 0.1 |

###  Descrição
 Depois da reunião rapida, decidimos modificar algumas stack, visando a produtividade da equipe

### Criterios de aceitação

- [x] Todos confirmarem a novas mudanças

**Comment by francisco1code** [comment]
Atenção lembrando q as stack q estão em analise são python com django e ruby com rails.

**Comment by edsondearaujo** [comment]
Como não foi possível todos estarem presentes nessa reunião rápida e levando em consideração a urgência de decidir o que vai mudar com relação as tecnologias, todos os membros da equipe irão se reunir hoje para chegar a uma conclusão.

**Comment by gabrielapivetta** [comment]
Achei [esse link](https://www.google.com/amp/s/railsware.com/blog/python-vs-ruby-vs-node-js-which-platform-is-a-fit-for-your-project/amp/) explicando muito bem a diferença, assim como vantagens e desvantagens entre:
- Python Django
- Ruby on Rails 
- Node.js com Express

**Comment by gabrielapivetta** [comment]
Decidimos, em reunião, manter a tecnologia que já haviamos escolhido previamente: Node.js, pois já temos mais experiência com ela e se adequa bem ao escopo do projeto. Também utilizaremos Express, Bootstrap e JQuery.
