### ISSUE TITLE
Controle de Arquivos da Documentação	

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#27]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Controle de Arquivos da Documentação| Organizando e criando | Documentation | @francisco1code  | - |

### Descrição
Foi criada algumas pastas e arquivos para organizar o mecanismo de documentação
* Pastas Criadas
   * Diagramas
   * Imagens
* Arquivos criados .MD
    - [x] Diagrama de caso de uso
   - [x]  Metodologia
   - [x]  Backlog do produto

**Atenção os checkbox que estão selecionado estão completos** 
### Criterio de aceitação

- [x] Concluir Toda documentação

**Comment by edsondearaujo** [comment]
### Referências sugeridas por Victor Moura na Call do dia 08/09

Repositório de open source real
[Watchtower](https://github.com/containrrr/watchtower)

Repositório do trabalho de EPS 
[Reabilitação motora](https://github.com/fga-eps-mds/2018.1-Reabilitacao-Motora)

Organização do trabalho de Desenho 
[GitPub](https://github.com/Desenho2018-2-GitPub)
[GitPub core](https://github.com/Desenho2018-2-GitPub/core)

**Comment by GeiseSaunier** [comment]
Finalizei a metodologia, gente! Quem puder dar uma revisada seria muito válido.

**Comment by GeiseSaunier** [comment]
Utilizei o padrão sugerido pelo Victor.

**Comment by francisco1code** [comment]
@GeiseSaunier  Documento de Metodologia Revisado.

**Comment by francisco1code** [comment]
Os Documentos que estava na pasta de doc/ fora todo movidos para a pasta wiki/, essa mudança foi feita por padrões de projeto, @edsondearaujo  @GeiseSaunier  @gabrielapivetta @liversonp  @Giuulob89
