### ISSUE TITLE
Preparar Ambiente do Desenvolvimento Back-End

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#32]
# Preparar Ambiente do Desenvolvimento

## Descrição
Preparando o habiente para desenvolvimento.

## Critério de aceitação

- [x] Criar estrutura basica para o node
- [x] Configurando docker
- [x] Configurando docker-compose
- [x] Configurando banco de dados
- [x] Organizando arquivos e pastas

**Comment by GeiseSaunier** [comment]
Ambiente de desenvolvimento configurado. Francisco, Edson e eu trabalhamos nessa parte!

**Comment by edsondearaujo** [comment]
Beleza @francisco1code . Vou configurar o Banco de Dados

**Comment by francisco1code** [comment]
@edsondearaujo cola na sala jits q dou uma ajuda!

**Comment by edsondearaujo** [comment]
Vamos pesquisar mais sobre o problema que estamos enfrentando na configuração do Postgresql.

**Comment by francisco1code** [comment]
@edsondearaujo  consegui achar um provável solução, para o erro no arquivo  /etc/apt/sources.list.d/pgdg.list

**Comment by edsondearaujo** [comment]
Legal @francisco1code , isso resolveu uma parte do problema. Existia um erro no nome do arquivo pgdg.list.

**Comment by francisco1code** [comment]
vi lá  @edsondearaujo  q acabou dando errado algumas parte, depois vou pesquisar mais a fundo para resolvemos esse problema até manhã.

**Comment by edsondearaujo** [comment]
@francisco1code  mais um avanço. Fiz duas mudança no arquivo _postgresql.conf_ para que outras máquinas consigam ter acesso ao banco de dados. De acordo com esse [Tutorial](https://www.vivaolinux.com.br/dica/Instalando-o-PostgreSQL-e-pgAdmin3-no-Ubuntu) precisamos fazer mais uma configuração para restringir o acesso ao banco de dados por IP.

**Comment by francisco1code** [comment]
@edsondearaujo  Blz edson, acabei de dar uma olhada nesse tutorial, hoje podemos no reunir na sala do jitsi para terminar a configuração dos bancos.

**Comment by edsondearaujo** [comment]
Parece que está tudo certo com a configuração. Só falta conectar o banco de dados com o back-end, Certo? @francisco1code

**Comment by francisco1code** [comment]
@edsondearaujo  Isso mesmo, tinha achando alguns bugs mais já resolvi, vou sou termina a configuração para fechar essa issue.

**Comment by francisco1code** [comment]
Configuração do ambiente back-end concluido.
