### ISSUE TITLE
Cadastrar usuário: Cliente tripulante

### ISSUE THREAD

**Issue by liversonp** [fga-eps-mds/2020-1-Ziguen#34]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Cadastrar usuário cliente | Cadastrar usuário cliente | back-end | @liversonp @GeiseSaunier    | 0.1 |
## Descrição

- [x] Criar o cadastro de usuário cliente tripulante

- [x] Fazer login

- [x] Editar usuário

- [x] Listar usuários

- [x] Excluir conta

- [x] Ter descrição do usuário

## Critério de aceitação

- [x] Ter todas as funcionalidades criadas

**Comment by GeiseSaunier** [comment]
https://www.youtube.com/watch?v=ghTrp1x_1As Esse vídeo é muito bom sobre API REST, o que vamos criar para o back.

**Comment by GeiseSaunier** [comment]
https://www.hostgator.com.br/blog/api-restful/ Esse outro também.

**Comment by GeiseSaunier** [comment]
Seria muito bom se vocês tirassem um tempinho para ler.

**Comment by liversonp** [comment]
https://www.youtube.com/watch?v=7NfvC-gOcRc& esse link aqui apesar de estar em espanhol, ajuda em relação ao Nodejs e PostgreSQL

**Comment by edsondearaujo** [comment]
Vou reabrir essa issue para fazer teste na criação do roadmap no zenhub. #74
