### ISSUE TITLE
Usuário Adiministrador

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#35]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Cadastrar usuário adm | Cadastrar usuário Adiministrador | back-end | @francisco1code  @edsondearaujo    | 0.1 |
## Descrição
- Contruir uma estrutura que seja possivel.
- [x] Cadastrar
- [x] Logar
- [x] Visualizar
- [x] Editar
- [x] Excluir

## Critério de aceitação

- [x] Testar as estruturas cadastrar, logar,  visualizar, editar e excluir, todos os teste feito com  o banco de dados.

**Comment by edsondearaujo** [comment]
@francisco1code assisti o [vídeo](https://www.youtube.com/watch?v=t4y9AFY9mmI&ab_channel=TipsCode) que você me mandou, para uma primeira apresentação, achei bem legal. Como não tenho experiência com Node.js, estou pesquisando na rede e estudando por meio desse  [curso](https://www.youtube.com/watch?v=LLqq6FemMNQ&list=PLJ_KhUnlXUPtbtLwaxxUxHqvcNQndmI4B&ab_channel=VictorLima-GuiadoProgramador) , parece bem organizado e vi que o curso aborda temas fundamentais para o nosso projeto. Como o framework Express.js, ensina fazer deploy na Heroku, nesse caso quero entender melhor essa parte de deploy, o curso apresenta também ferramentas como o Nodemon e muito mais conteúdo.

**Comment by francisco1code** [comment]
@edsondearaujo  esse material q te mandei é bem interresante para ter uma visão geral do q iremos fazer nessa sprint  e quais framework iremos usar nessa fase inicial do projeto.

**Comment by edsondearaujo** [comment]
Ambiente de desenvolvimento configurado #32 , yarn e Nodejs instalados. Estou pronto para começar a desenvolver o CRUD do Admin.

**Comment by edsondearaujo** [comment]
Houve um atraso na iniciação da implementação devido problemas técnicos discutidos na issue #32

**Comment by RochaCarla** [comment]
Revisar a descrição da issue.. pensar em uma issue template para facilitar o preenchimento. Quais são as tarefas para implementar um crud ? quais sao os critérios de aceitação (como testar para garantir que o crud foi implementado corretamente)?

**Comment by GeiseSaunier** [comment]
Obrigada pela contribuição, professora. Iremos revisar.

**Comment by edsondearaujo** [comment]
Depois de tantos bugs, finalizamos a implementação do usuário do administrador.
