### ISSUE TITLE
Estudar Gitflow

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2020-1-Ziguen#4]
Entender quais como funciona o gitflow e entender os principais comandos do gitflow :P

- [x] Procurar boas referencias de tutoriais

- [x] Documentar o padrão gitflow a ser adotado pelo time

# Critério de Aceitação

- [x] A documentação estar disponível no repositório do time e revisada

**Comment by edsondearaujo** [comment]
Reabri a issue para darmos continuidade na documentação do treinamento de Gitflow.

**Comment by edsondearaujo** [comment]
### Referências
 

1. [ TCC ](https://bdm.unb.br/handle/10483/21938) de Daniel Almeida do curso de ciência da computação na UnB.
***Título:*** Roger-that flow : um uso aprimorado do git-flow
Publicado em 2018
2. [Gitflow na prática](https://www.youtube.com/watch?v=wzxBR4pOTTs). Esse vídeo mostra alguns fluxos de trabalho no git e como funciona o gitflow

**Comment by Giuulob89** [comment]
Achei que esse site explica muito bem sobre o assunto: https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by liversonp** [comment]
encontrei um vídeo que eles dão uma ótima visão sobre o gitflow e deixam as coisas bem explicadas: https://www.youtube.com/watch?v=oweffeS8TRc

**Comment by francisco1code** [comment]
Todos os materias são de excelente qualidades, vlw galera!

**Comment by gabrielapivetta** [comment]
Muito boas as referências!

**Comment by GeiseSaunier** [comment]
As referências são ótimas! Gostei também. Andei estudando e testando alguns comandos.

**Comment by GeiseSaunier** [comment]
Galera, esse vídeo curto explica muito bem o padrão gitflow. Vale a pena dar uma conferida: https://www.youtube.com/watch?v=oweffeS8TRc&t=325s.

**Comment by edsondearaujo** [comment]
Vou reabrir essa issue para fazer teste na criação do roadmap no zenhub. #74
