### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by Giuulob89** [fga-eps-mds/2020-1-Ziguen#40]
| Nome | Assunto | Labels | Assignees |
| -- | -- | -- | -- |
| Protótipo de Baixa Fidelidade | Desenvolvimento do Protótipo | Front-End, Protótipo e Documentation | @Giuulob89 @gabrielapivetta |

# Descrição
Execução de protótipo de baixa fidelidade para visualização do projeto e para facilitar a execução do de alta fidelidade.

# Tarefas

- [x] Definir os atributos de cada tela

- [x] Executar a base do protótipo

# Critérios de Avaliação

- [x] Alterações no protótipo base

- [x] Aprovação da equipe

**Comment by gabrielapivetta** [comment]
Eu, a @Giuulob89 e o @francisco1code reunimos para avaliarmos o andamento do protótipo de alta fidelidade e vimos a necessidade de planejarmos melhor os requisitos de cada tela e para isso faremos o protótipo de baixa fidelidade.

**Comment by Giuulob89** [comment]
Eu, a @gabrielapivetta  e o @edsondearaujo discutimos sobre como serão alguns dos dados de usuários, focando mais na questão do CPF. Todos os usuários irão cadastrar CPF, além das outras informações já definidas.

**Comment by edsondearaujo** [comment]
Precisamos refletir mais sobre a tela do Admin. Não acho viável fazer uma solicitação direta no Banco de Dados.

**Comment by Giuulob89** [comment]
Para facilitar a visualização, foi criada uma pasta no Drive chamada [Protótipos](https://drive.google.com/drive/folders/15fcqZRMxOijFy9bdFBDHxCjmR5HLcnMp?usp=sharing) com as imagens do que seriam as telas (por enquanto, apenas referentes as da visualização do Admin. As outras serão feitas ao longo da semana e iremos atualizando o Drive). Gostaríamos da opinião de vcs, o que poderia mudar, acrescentar ou retirar. @GeiseSaunier @edsondearaujo @liversonp.

**Comment by GeiseSaunier** [comment]
Vou dar uma olhada hoje, galera. Em seguida, dou minha opinião.

**Comment by GeiseSaunier** [comment]
Gente, acredito que só precisa mudar o "numero de assentos" para "número máximo de tripulantes suportados", algo do genêro. Mas os demais estão ok. Parabéns, meninas.

**Comment by gabrielapivetta** [comment]
Beleza @GeiseSaunier, atualizamos e criamos as telas do Dono da Embarcação

**Comment by Giuulob89** [comment]
@GeiseSaunier @edsondearaujo @francisco1code @liversonp analisem e vejam o que mais pode ser alterado. Vamos fazer telas do cliente na Quinta Feira.

**Comment by edsondearaujo** [comment]
Ok, @Giuulob89 , te dou um feedback no mais tarde amanhã

**Comment by edsondearaujo** [comment]
@gabrielapivetta e @Giuulob89 a equipe do Back-end se reuniu para discutir sobre o usuário proprietário.
Segue um breve feedback sobre a tela do proprietário do protótipo de fidelidade.

**Tela do Proprietário:** 
- Não entendi o botão, **_tela inicial_** na home do proprietário. Acredito que não vamos ter esse campo aí, dentro da tela _home_
- Retirar o botão **_editar perfil_**. Como estávamos tendo problemas com o usuário proprietário, entramos em um acordo, onde o usuário proprietário, não fará nenhuma manipulação de dados dentro do sistema, isso vai ficar com o usuário administrador.
- Com a retirada do botão **_editar perfil_**, não vamos precisar da tela de edição do perfil, dentro do espaço do proprietário, essa tela pode ficar com o administrador.
- Em **_visualizar embarcações_**, podemos tirar o botão viagens e deixar somente o **_botão embarcação_**. O proprietário clica no botão embarcação e o sistema abre uma página contendo todas as informações de tal embarcação, inclusive as viagens.
- Na tela viagens, acho válido pensar em uma forma de mostrar os dados relacionados ao número de viagens (realizadas, futuras e total) em um campo com uma quebra de linha. Acredito que vai ficar mais intuitivo o quadro com essas informações, pode ser um campo pequeno, discreto.

_**Rascunho da mudança que vamos fazer no DER**_ #20 
![rascunho_der](https://user-images.githubusercontent.com/39536164/93364339-ce2d3d00-f81e-11ea-9910-f3d752f9a19b.jpg)

**Comment by edsondearaujo** [comment]
Depois dessa mudança no diagrama de entidade e relacionamento #20 , consequentemente vamos ter ajustes na tela do administrador.

**Comment by francisco1code** [comment]
Galera e faz o total sentindo fazer essas mudanças, aqui no back estava dando uma pequena confusão, mais o problema já foi solucionado.

**Comment by gabrielapivetta** [comment]
Atualizamos as telas do admin e agora o dono da embarcação só tem uma tela mais intuitiva.

**Comment by Giuulob89** [comment]
Não serão feitos os protótipos de baixa fidelidade referentes ao tripulante, faremos direto o protótipo de alta fidelidade referente a ele.
