### ISSUE TITLE
Troca de banco de dados

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#41]
| Título| Assunto | Label | Assignees | Versão |
|------|------|------|-----|----|
| Troca de banco de dados | Bnaco de dados | Banco_Dados | @francisco1code  @edsondearaujo    | 0.1 |
## Descrição
Foi feita a troca de banco de dados de sqlite para  postgres

## Critério de aceitação

- [x] Decisão unânime da equipe de back-end

**Comment by francisco1code** [comment]
A equipe do back-end se reuniu para tomar essa decisão tecnica.

**Comment by edsondearaujo** [comment]
Depois de uma breve pesquisa decidimos que o Postgresql vai ser melhor para gente trabalhar, a linguagem do Postgresql é basicamente javascript. A equipe tem mais conhecimento nessa linguagem.

**Comment by liversonp** [comment]
Estou de acordo com a decisão, estava vendo alguns vídeos e normalmente quando se trata do node, normalmente o Postgresql está vinculado
