### ISSUE TITLE
Implementação da home

### ISSUE THREAD

**Issue by GeiseSaunier** [fga-eps-mds/2020-1-Ziguen#45]
| Nome | Assunto | Label | Assignees |
|---|---|---|---|
| Implementação da home | Criar a home da Ziguen| front-end | @GeiseSaunier  |

# Descrição
Implementar a home do sistema, de acordo com o padrão definido no protótipo de alta fidelidade.

# Tarefas

- [x] Implementar a home

# Critérios de Aceitação

- [x] A home estar pronta e funcional de acordo com o protótipo

- [ ] Aprovação da Equipe

**Comment by edsondearaujo** [comment]
Oi, @GeiseSaunier . Parabéns pelo [código](https://github.com/fga-eps-mds/2020-1-Ziguen/blob/develop/home/index.html), fez bastante coisa. Para não ficar sobrecarregada e por termos um template com algumas regras, sugiro que  siga a [política de commits](https://github.com/fga-eps-mds/2020-1-Ziguen/blob/develop/docs/templates/commit_template/commit_policy.md), acredito que esteja seguindo, vi seus [commits](https://github.com/fga-eps-mds/2020-1-Ziguen/commits/develop) bem separados, boa! Mas é sempre bom lembrar.  E como discutimos em conversa com o grupo, por questão de organização e esse repositório ser uma API Rest do back-end, o grupo tem um novo repositório para o [front-end](https://github.com/fga-eps-mds/2020.1-Ziguen-Front/tree/master) .  O embasamento teórico para chegar a essa decisão, foi praticamente uma conversa com a [Sara Silva](https://github.com/silvasara) aluna de EPS que está no projeto [Stay-safe-secretary-service](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service) e uma consulta com o [Victor Moura](https://github.com/victorcmoura) que vem nos monitorando em alguns processos do projeto.
Gostaria de lembrar a importância de seguir o [Panning da sprint](https://github.com/fga-eps-mds/2020-1-Ziguen/blob/develop/docs/sprints/planning/sprint4.md), essa implementação da [home](https://github.com/fga-eps-mds/2020-1-Ziguen/tree/develop/home) não está no nosso planejamento da semana e, não que isso te impeça de ajudar a equipe do front, mas você está alocada para o back-end. Quero reforçar que se estiver tendo algum tipo de dificuldade, fale com o grupo ou com alguém no privado se preferir, vamos nos ajudar a compreender essa fase teórica da disciplina [mds](https://github.com/fga-eps-mds).

**Comment by GeiseSaunier** [comment]
Sim, Edson. Compreendi, mas é que eu decidi criar pra já criar uma requisição para o banco. Mas irei trabalhar sim no back do usuário esse semana.

**Comment by edsondearaujo** [comment]
Certo Geise. Eu coloquei um tópico no [README](https://github.com/fga-eps-mds/2020-1-Ziguen) desse repositório, referenciando o repositório do front. Mas creio que cometi um erro de sintaxe no HTML que não gerou o link. Amanhã eu resolvo essa questão.
