### ISSUE TITLE
Avaliação -  Casos de Uso

### ISSUE THREAD

**Issue by gag2502** [fga-eps-mds/2020-1-Ziguen#47]
- Não é necessário essas setas representando o relacionamento entre os atores. Não está errado, mas no caso do diagrama de vocês ficou confuso e não é algo indispensável para compreensão.
- Casos de uso para CRUD podem ser resumidos em apenas 1: manter conta.
- Não é necessário um caso de uso de entrar no sistema, porque é muito básico. Procurem inserir no trabalho de vocês apenas elementos realmente relevantes, beleza ? ;-)
- Dúvida: O usuário pode visualizar a passagem sem antes pesquisar? Se não for o caso, o diagrama deve ser alterado.
- Usem e abusem de cores no diagrama de vocês! =)

**Comment by liversonp** [comment]
No caso a intenção seria de conseguir visualizar a passagem que comprou, mas vou dar uma corrigida pra ficar mais claro
