### ISSUE TITLE
Avaliação - DER

### ISSUE THREAD

**Issue by gag2502** [fga-eps-mds/2020-1-Ziguen#48]
- Não é necessário colocar as chaves estrangeiras no DER. As chaves estrangeiras devem aparecer nas entidades no diagrama lógico.

**Comment by edsondearaujo** [comment]
Beleza @gag2502 . vou fazer esses ajustes. #20 
Obrigado pela dica.

**Comment by GeiseSaunier** [comment]
Obrigada pela sugestão, @gag2502!

**Comment by francisco1code** [comment]
Vlw @gag2502
