### ISSUE TITLE
Avaliação - Diagrama de metodologia

### ISSUE THREAD

**Issue by gag2502** [fga-eps-mds/2020-1-Ziguen#49]
- Vocês não estão incluindo o rito de retrospectiva? Se esse for o caso, recomendo fortemente que o façam. 
- "issue normais" não é um bom nome para issues de bugs e suporte. Vou deixar vocês darem um nome melhor pra elas, viu? ;-)
- As issues são priorizadas? Se não forem, recomendo fortemente que o façam. As issues devem ser priorizadas por um PO ou um membro da equipe que desempenhe esse papel dentro da equipe ou similar papel. As sprints devem estar sendo direcionadas para a solução do problema negocial de acordo com a necessidades prioritárias dos clientes e/ou usuários.
- Usem e abusem de cores no diagrama de vocês! =)

**Comment by GeiseSaunier** [comment]
Compreendi, @gag2502! Muito obrigada! Iremos rever esses detalhes.
