### ISSUE TITLE
Estudar documento de Visão

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2020-1-Ziguen#5]
Entender o Documento de Visão de um projeto de software.

# Tarefas
- [x] Procurar templates de Documento de Visão

- [x] Analisar Documentos de Visão de projetos dos semestres anteriores

- [x] Escolher um template de Documento de Visão a ser adotado

# Critério de Aceitação

- [x] Template revisado

- [x] Documentar em isso o que precisa ser feito/pesquisado/decidido para construir um documento de visão

**Comment by RochaCarla** [comment]
Estou adora

- [ ] gafga[](url)

**Comment by ErickGiffoni** [comment]
Oi !
Passando aqui para deixar para vcs um exemplo de documento de visão do projeto que participei em MDS : 
- https://fga-eps-mds.github.io/2019.1-ADA/#/docs/product/vision_document 
Foi um chatbot, chamado Ada. Nesse link acima vcs vão conseguir ver outros exemplos de documentos, como Arquitetura etc.
Espero ter ajudado =)

**Comment by edsondearaujo** [comment]
Satisfação @ErickGiffoni. Agradeço em nome do grupo por sua disposição em colaborar nos fornecendo esse material. Vai ajudar sim :)

**Comment by francisco1code** [comment]
### Procurar Templates de Documento de Visão

**[Estrutura de Documento de Visão](https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html)** 
* Introdução
* Posicionando
* Descrições da Parte Interessada e do Usuário
* Visão Geral do Produto
* Recursos do Produto
* Restrições
* Faixas de Qualidade
* Precedência e Prioridade
* Outros Requisitos do Produto
* Requisitos de Documentação

**Comment by edsondearaujo** [comment]
Realizamos pesquisas em repositórios dos semestre anteriores afim de estudar, observar modelos e discutir sobre o que é um documento de visão.
Iniciamos a documentação e o processo está sendo registrado em #18

**Comment by edsondearaujo** [comment]
#74
