### ISSUE TITLE
Avaliação - Sprints

### ISSUE THREAD

**Issue by gag2502** [fga-eps-mds/2020-1-Ziguen#51]
- Vi que vocês colocaram um tópico retrospectiva no documento da sprint, mas cuidado! Dívidas técnicas não são suficientes numa retrospectiva. Elas são mais adequadas ao tópico de revisão e na retrospectiva vocês devem listar pontos positivos e negativos da sprint. 
- Li que vocês pesquisaram para escolher as tecnologias e é isso aí! Muito bem! Essa é uma parte bem importante. Mais importante que isso é decidir a arquitetura do sistema. Estou ansiosa pelo documento de arquitetura de vocês! Arrasem!
- Dúvida: Vocês não vão usar nenhum framework ou biblioteca para desenvolver? Eu recomendo fortemente que vocês pesquisem e escolham uma. Só de bibliotecas JS vocês vão encontrar várias! É importante vocês conhecerem e usarem as tecnologias que estão sendo usadas no mercado para não reiventar a roda. Não deixem para pesquisar isso na hora do desenvolvimento!
- Já posso dizer que não só de JUnit que vive um teste rs Brincadeiras a parte, se vocês desejam mesmo usar o JUnit pesquisem sobre o Mockito e o Rest Assured, são ferramentas que auxiliam no desenvolvimento dos testes com o JUnit.
- Uma outra tecnologia que vocês podem e devem pensar para testes é o Cypress, bem útil para testes de frontend.
- Não se apeguem apenas às tecnologias que citei. Voem em busca de algo melhor ou que se encaixe melhor no cenário de vocês.
- Palpite: Talvez o Junit não seja a melhor saída para testes de unidade em código Javascript (Node.js). Talvez... 
- Estou muito curiosa para saber como Python e C++ irão ser usados por vocês no pipeline de desenvolvimento. Novidade para mim =) Arrasem!
- Diquinha: Pensem, se ainda não pensaram, no fluxo de desenvolvimento. Como serão feitos os commits? Como vamos nomear as branches? e muitas outras coisas! Pesquisem por: Gitflow.
- Usem e abusem de cores na documentação de vocês! =) Já pensaram em um Github pages ? Algo bem legal, mas bem opcional.

**Comment by edsondearaujo** [comment]
Opa! Precisamos entender melhor como fazer a retrospectiva e dívidas técnicas então. 
Sobre as tecnologias, tomamos algumas decisões, mas talvez não tenha ficado bem documentado. Não iremos usar Python e C++. O JUnit também não está 100% definido se vamos usá-lo. temos algumas tecnologias listadas nessas issues #10 , #26 .

**Comment by GeiseSaunier** [comment]
Quanto aos commits, nós estamos usando o padrão gitflow, sim. Nós padronizamos os commits, criamos templates para as issues também, etc. Tem um tópico na documentação que deixa isso bem mais detalhado. 
Vamos pensar melhor a respeito das tecnologias e retrospectivas. Muito Obrigada!
