### ISSUE TITLE
Conselhos para cada um dos membros da Equipe

### ISSUE THREAD

**Issue by gag2502** [fga-eps-mds/2020-1-Ziguen#52]
- **Gabi**: Amiga, se esforce para aprender como se virar bem com o Git. Mas, relaxa! É um aprendizado contínuo e o Google vai te ajudar bastante com isso! ;-) Você é a que tem mais debilidade técnica. Eu aconselho você a não deixar de se desafiar! O aprendizado é um motor que só funciona a base de motivação. Esse caminho nem sempre é simples, mas somos capazes e acredito em você.
- **Giulia**: Amiga, sinto que você tem habilidade no frontend, tô errada? rs Conhecer sobre HTML e CSS é muito importante, mesmo usando um Framework para frontend e o Bootstrap. Experimenta o desenvolvimento frontend, estou com uma boa expectativa de que você vai gostar.
- **Liverson**: Amigo, assim como a Giulia, parece que você tem habilidade com tecnologias usadas no desenvolvimento frontend e isso é muito bom! Não deixe de experimentar essa área do desenvolvimento. A parte mais básica você já tem, de agora em diante o céu é o limite!
- **Geise**: Amiga você A-R-R-A-S-A !!! Olha... tô sentindo cheiro de backend e devops viu... #FicaADica. Você tem uma boa bagagem de conhecimento e tudo pra caminhar rumo ao Full-stack. Ajude seus coleguinhas a crescerem junto com você. Espalhe amor e conhecimento por onde você for...
- **Edson**: Amigo, vi que você teve experiência com Python. Um passo fundamental para experimentar o Django, que vocês escolheram. Pelas tecnologias que você já teve contato, chuto que você vai se amarrar no desenvolvimento backend!
- **Francisco**: Amigo, você já experimentou bastante coisa! Parabéns! Aproveite essa disciplina pra avançar ao próximo nível ;-) Vi que assim como a Geise, você teve um bom contato com Node.js, e isso é bem legal! Compartilhe conhecimento com seus colegas, nunca guarde pra você =) E um pequeno palpite: backend parece ser sua praia! Arrase!

**Comment by gabrielapivetta** [comment]
Oi Gabi, você olhou a tabela de conhecimentos? Agradeço o feedback, mas achei válido vir me justificar também, lá nós mesmos nos julgamos e eu sempre prefiro talvez subestimar do que superestimar algum conhecimento meu. Gostaria de saber qual foi a base do feedback, para que se realmente foi a tabela eu possa ser mais realista nas próximas autoavialiações. @gag2502

**Comment by edsondearaujo** [comment]
Eu ia fazer a mesma pergunta da @gabrielapivetta :) imagino que sim, talvez nossa documentação não esteja bem explicadinha, porque tomamos decisões e continuamos tomando, o quadro de conhecimento mais atual é o da sprint 3, onde não tem Python como tecnologia. De qualquer forma agradeço o feedback e acredito que vai nos ajudar a observar alguns pontos que podemos melhorar. Obrigado @gag2502

**Comment by GeiseSaunier** [comment]
Oi, @gag2502! Muito Obrigada! Full-stack eu não sei, mas eu AMO desenvolvimento back-end. Pretendo trabalhar aprimorando meus conhecimnetos nessa área. 
Mais uma vez, obrigada por surgir e nos dar direcionamento no projeto.
