### ISSUE TITLE
Oiiiiê! Trouxe mimos para vocês pessoal! =) - 1ª Avaliação.

### ISSUE THREAD

**Issue by gag2502** [fga-eps-mds/2020-1-Ziguen#53]
Olá pessoal do Ziguen! Eu sou a Gabi, colega de vocês do 10º semestre (ou mais). Estou aqui para dar uma ajudinha no andamento do projeto de vocês! 
De modo geral, quero dar os parabéns a vocês! Estão bem empenhados e isso é muito bom. Vi que estão engajados, presentes em todas as reuniões, se organizando e isso é ótimo!  Continuem nesse bom ritmo que é sucesso.
Vou colocar abaixo as issues de avaliação separadas por tópicos! =)

#47 Casos de Uso
#48 DER
#49 Diagrama de Metodologia
#50 Diagrama de Sequência
#51 Sprints
#52 Conselhos

**Comment by edsondearaujo** [comment]
Que bom que apareceu para nos dar um apoio @gag2502 . Vamos te procurar para tirar duvidas :)
Grato.

**Comment by GeiseSaunier** [comment]
Muito obrigada por surgir, @gag2502! Entraremos em contato para eventuais dúvidas.
