### ISSUE TITLE
Embarcação

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#55]
### Implementar funcionalidade Embarcação

- [x] Create
- [x] List
- [x] Update
- [x] Delete

### Critério de aceitação
- [x] A implementação deve permitir o usuário realizar todos os passos listados acima

**Comment by edsondearaujo** [comment]
Tudo ok.

**Comment by edsondearaujo** [comment]
Acrescentar implementação, capacidade da embarcação.
