### ISSUE TITLE
integrar o back com o front

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#63]
| nome | assunto| label | assignees |
|------|------|------|-----|
|  integrar o back com o front | comunicação do back com o front  |  Devops |   Grupo | 

## Descrição

Buscar ferramentas, pesquisar, estudar formas de fazer a integração do backend com o frontend.

## Tarefa 

- [x] Pesquisar/estudar ferramentas
- [x] Trazer solução

## Critério de aceitação
- [x] Comunicação realizada com sucesso

**Comment by edsondearaujo** [comment]
@liversonp faça as honras de fechar essa issue.
