### ISSUE TITLE
Mudança no front-end 

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#65]
| nome | assunto| label | assignees |
|------|------|------|------|
| Front-end | Mudanças | front-end| @francisco1code | 

## Descrição
Levantamento de informações sobre a mudança de frame work do front-end.

## Tarefa 

- [x] Fazer levantamento das provaveis tecnologias

**Comment by gabrielapivetta** [comment]
Pelo que entendi podemos fazer a integração com React, mas para isso temos que tirar o bootstrap... ou para poder continuar com o bootstrap, teríamos que usar React-Bootstrap com Next.js. Se for essa a situação, acredito que seja mais viável retirar o bootstrap, já que as telas não estão 100% baseadas nele, e assim só precisaríamos incluir o React.

**Comment by francisco1code** [comment]
(Resposta para a pergunta o pq que usar o react) então, por nosso back-end ser um API, o front-end meio q precisar ter um "servidor proprio", da maneira que estava sendo desenvolvido (css, html, boostrap) não estavam usando nenhum tipo de framework que faça essa funcionalidade. O [react.js](https://pt-br.reactjs.org/) é uma das opções, inclusive uma das melhores opções na minha opinião.

**Comment by francisco1code** [comment]
Teoricamente vc pode escolher qualquer outra lingugem e framework para fazer o front, pq indepedente disso vc consegui consumir os dados da API
