### ISSUE TITLE
Estudar Documento de Arquitetura 

### ISSUE THREAD

**Issue by GeiseSaunier** [fga-eps-mds/2020-1-Ziguen#7]
**Compreender os conceitos acerca de Arquitetura de Software**

## Tarefas

- [x] Pesquisar boas referências;

- [x] Entender os modelos de Arquitetura;

- [x] Reunir com o grupo e apresentar os modelos encontrados;

- [x] Escolher em conjunto a que mais se adequa ao problema;

## Critério de Aceitação 

- [x] Tarefas revisadas;

- [x] Documentar em issue as decisões e organizar o documento de arquitetura;

**Comment by GeiseSaunier** [comment]
https://www.igti.com.br/blog/arquitetura-de-software-definicao-negocios/

Galera, gostei muito desse link. Ele traz uma abordagem geral sobre a Arquitetura de Software, em seguida lista alguns tipos e explica cada uma delas. A linguagem é bem acessível. Acho que vale muito a pena dar uma "atençãozinha" quando puderem.

**Comment by GeiseSaunier** [comment]
http://docs.computacao.ufcg.edu.br/posgraduacao/dissertacoes/2009/Dissertacao_GuilhermeMauroGerrmoglioBarbosa.pdf

Esse outro é uma Dissertação. Ele apresenta com mais detalhes os modelos de Arquitetura, além disso explica os conceitos relevantes quanto a escolha. Ele é bem completo. Gostei bastante também.

**Comment by GeiseSaunier** [comment]
http://www.inf.ufpr.br/andrey/ci163/PadroesFrameworksAl.pdf

Esse aborda os tipos de frameworks quanto ao escopo escolhido. Está inserido nos padrões para a escolha da arquitetura, claro. Está separado por tópicos e isso facilita bastante.

**Comment by GeiseSaunier** [comment]
Continuarei com as pesquisas. Qualquer material relevante, compartilho com vocês. Fiquem em casa. Se preciso sair, usem máscara. Bons estudos e um bom fim de semana!

**Comment by gabrielapivetta** [comment]
Li os links disponibilizados, são muito informativos e simples de entender. Podemos debater mais na próxima reunião.

**Comment by edsondearaujo** [comment]
#74
