### ISSUE TITLE
Estudo Open Source

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#8]
Entender a dinâmica da comunidade open source e suas tecnologias

# Tarefas

- [x] Realizar pesquisa sobre a cultura Open Source

- [x] Levantamento de tecnologias Open Source

# Critérios de aceitação

- [x] Pesquisa revisada

**Comment by francisco1code** [comment]
# Estudo Open Source
![a](https://raw.githubusercontent.com/francisco1code/gfinp/master/imagens/a.gif)

### Cultura Open Source
[Leitura - Cultura open source, liberdade e software livre](https://dev.to/arielbarcellos/cultura-open-source-liberdade-e-software-livre-4k7o)
[Video - O que é software open source?](https://www.youtube.com/watch?v=x4JwObY4xZc&feature=youtu.be)

### Tecnologias Open Source
[Leitura - Como o open source está definindo as tecnologias do futuro](https://canaltech.com.br/software/como-o-open-source-esta-definindo-as-tecnologias-do-futuro/)
[Leitura - Algumas tecnologias Open Source para o Linux](https://canaltech.com.br/linux/20-alternativas-de-programas-famosos-do-windows-para-linux/)
[Video - 20 Alternativas Open Source dos seus Aplicativos favoritos](https://www.youtube.com/watch?v=fM3d3tTxcHQ)

**Comment by edsondearaujo** [comment]
@francisco1code Li os textos e assisti aos vídeos da pesquisa. Fiz uma alteração nos títulos das leituras e vídeos na intenção de não deixar dúvidas no que se refere cada link. Assim, que der revise minhas alterações e se tiver de acordo, fique à vontade para fechar a issue.

**Comment by edsondearaujo** [comment]
#74
