### ISSUE TITLE
Pipeline CI

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#87]
| nome | atividade | label | assignees |
|------|------|------|-----|
| Pipeline CI | Implantar o método CI | Devops  | @gabrielapivetta , @francisco1code, @edsondearaujo    | 

## Descrição
Aplicar automação nas etapas do desenvolvimento.
   
## Tarefa 
   - [x] levantar pesquisa sobre integração contínua _(CI-continuous integration)_.
   - [x] Estudar a pesquisa que foi realizada.
   - [x] Documentar na issue, o caminho percorrido para a realização da atividade. 

## Critério de aceitação
- [x] Checkbox das tarefas, preenchidos.
- [x] A implantação do método deve estar funcionando corretamente.
- [x] Pelo menos dois membros do grupo devem verificar a atividade.

**Comment by francisco1code** [comment]
**Material Principal:** utilizei a [Documentação do Travis-CI](https://docs.travis-ci.com/user/tutorial/)

**Comment by francisco1code** [comment]
**Material complementer:** usei esse [Projeto](https://github.com/fga-eps-mds/2019.2-Gymnasteg-Backend) do semestre passado como base.
