### ISSUE TITLE
Pipeline CD

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020-1-Ziguen#88]
| nome | atividade | label | assignees |
|------|------|------|-----|
| Pipeline CD | Implantar o método CD | Devops  | @gabrielapivetta , @francisco1code, @edsondearaujo    | 

## Descrição
aplicar automação nas etapas do desenvolvimento.
   
## Tarefa 
   - [x] levantar pesquisa sobre entrega contínua _(CD-continuous delivery)_.
   - [x] Estudar a pesquisa que foi realizada.
   - [x] Documentar na issue, o caminho percorrido para a realização da atividade. 

## Critério de aceitação
- [x] Checkbox das tarefas, preenchidos.
- [x] A implantação do método deve estar funcionando corretamente.
- [x] Pelo menos dois membros do grupo devem verificar a atividade.

**Comment by edsondearaujo** [comment]
***Referência:***
[Red Hat](https://www.redhat.com/pt-br/topics/devops/what-is-ci-cd)
