### ISSUE TITLE
Diagrama lógico

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#89]
| nome | atividade | label | assignees |
|------|------|------|-----|
| Diagrama lógico | Criar diagrama lógico | diagram  | @GeiseSaunier  , @edsondearaujo   | 

## Descrição
Criar diagrama lógico para mapear o fluxo de dados do sistema.
   
## Tarefa 
   - [x] levantar pesquisa sobre diagrama lógico.
   - [x] Estudar a pesquisa que foi realizada.
   - [x] Documentar na issue, o caminho percorrido para a realização da atividade. 

## Critério de aceitação
- [x] Checkbox das tarefas, preenchidos.
- [x] O diagrama deve ser coerente com a documentação do projeto.
- [x] Pelo menos dois membros do grupo devem verificar a atividade.

**Comment by edsondearaujo** [comment]
### Referências
[Como elaborar Modelo Lógico](http://repositorio.ipea.gov.br/bitstream/11058/5810/1/NT_n06_Como-elaborar-modelo-logico_Disoc_2010-set.pdf)
[Diagrama de fluxo de dados Lógico x Físico](https://www.lucidchart.com/pages/pt/diagrama-de-fluxo-de-dados-logico-x-fisico)

**Comment by GeiseSaunier** [comment]
A gente gerou utilizando o BrModelo, mas ainda não consegui exportar com uma qualidade melhor. Vamos tentar resolver ainda.
