### ISSUE TITLE
Estudar protótipos de baixa alta/fidelidade

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2020-1-Ziguen#9]
Estudar protótipos de baixa alta/fidelidade com os detalhamentos necessários

## Tarefas

- [x] Pesquisar referências

- [x] Entender protótipos de baixa/alta fidelidade

- [x] Definir dimensões de fidelidade dos modelos

## Critério de Aceitação

- [x] Tarefas revisadas

**Comment by ErickGiffoni** [comment]
Oi !
Passando para deixar umas referências para vcs de trabalhos que eu participei sobre essa issue : 
- https://github.com/Interacao-Humano-Computador/2019.2-CodeForces/blob/devel/codeforces_docs/prototipacao/alta_fidelidade.md -> Alta fidelidade
- https://interacao-humano-computador.github.io/2019.2-CodeForces/concepcao/prototipo_de_papel/ -> baixa fidelidade
Ambos protótipos foram para a plataforma web do Codeforces.
Espero ter ajudado =)

**Comment by gabrielapivetta** [comment]
Obrigada pela contribuição, @ErickGiffoni !

**Comment by GeiseSaunier** [comment]
Muito obrigada, @ErickGiffoni!

**Comment by edsondearaujo** [comment]
Boa @ErickGiffoni 
Obrigado!

**Comment by gabrielapivetta** [comment]
Resumidamente, um Protótipo de Baixa Fidelidade é realizado no papel com a ideia inicial do projeto a ser desenvolvido. Já o Protótipo de Alta Fidelidade é feito em uma ferramenta computacional de forma mais detalhada.
Os links disponibilizados pelo Erick são muito explicativos e didáticos e existem links adicionais no primeiro. Quem puder acessá-los ajudará bastante no aprofundamento do tema.

**Comment by GeiseSaunier** [comment]
Revisei os links sugeridos e acredito que ajudarão bastante no desenvolvimento dessa etapa do projeto, visto que possui exemplos simples e claros acerca do tema proposto.

**Comment by ErickGiffoni** [comment]
Fico feliz em ter ajudado, vcs vão longe ! 👏🏻 👏🏻

**Comment by edsondearaujo** [comment]
#74
