### ISSUE TITLE
Atualizar diagrama casos de uso

### ISSUE THREAD

**Issue by liversonp** [fga-eps-mds/2020-1-Ziguen#90]
| nome | assunto| titulo| label | assignees |
|------|------|------|------|-----|
|Atualizar diagrama casos de uso  | Melhorar as informações do diagrama |  | Diagram | @liversonp @Giuulob89   | 

## Descrição
Por questão de melhorar o entendimento do nosso projeto, há a necessidade de tentar melhorar o diagrama de caso de uso e itens relacionados
   
## Tarefa 

- [x] Procurar em outros repositórios
- [x] Adicionar mais informações relacionadas ao 
- [x] Adicionar descrições de casos de 
- [x] Adicionar atores de casos de uso

**Comment by edsondearaujo** [comment]
Tudo certo com o diagrama, segundo o feedback da Gabi na release 1, o que podemos rever é como o diagrama está alocado dentro da documentação.
