### ISSUE TITLE
Atualizar Page

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#91]
| nome | atividade | label | assignees |
|------|------|------|-----|
| Atualizar Page | Atualizar a page | documentation  | @liversonp  , @francisco1code   | 

## Descrição
Atualizar e organizar a page do projeto.
   
## Tarefa 
   - [x] Revisar e fazer modificações onde for necessário.
   - [x] Criar sumário conforme for preenchendo a page.
   - [x] Criar link no sumário, direcionando para os tópicos e subtópicos. 
   - [x] Documentar na issue, o caminho percorrido para a realização da atividade. Ex: Dúvida sobre um tópico feito por outro membro. 

## Critério de aceitação
- [x] Checkbox das tarefas, preenchidos.
- [x] O sumário deve estar coerente com os tópicos apontados.
- [x] O grupo ou Scrum Master ou Product Owner verificar a atividade realizada.

**Comment by Giuulob89** [comment]
Galera, a base de como as imagens devem ficar no readme está nesse projeto: https://github.com/fga-eps-mds/2018.1_Gerencia_mais.git
