### ISSUE TITLE
Diagrama de pacotes

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#93]
| nome | atividade | label | assignees |
|------|------|------|-----|
| Diagrama de pacotes | Criar diagrama de pacotes | diagram  | @gabrielapivetta , @francisco1code   | 

## Descrição
Criar diagrama de pacotes para ilustrar a arquitetura do sistema.
   
## Tarefa 
   - [x] levantar pesquisa sobre diagrama de pacotes.
   - [x] Documentar na issue, o caminho percorrido para a realização da atividade. 

## Critério de aceitação
- [x] O diagrama deve ser coerente com a documentação do projeto.

**Comment by gabrielapivetta** [comment]
Decidimos adiar a criação do Diagrama de Pacotes porque ainda estamos estruturando o projeto e alterando algumas tecnologias.

**Comment by edsondearaujo** [comment]
### Referências

[IFRN](http://diatinf.ifrn.edu.br/prof/lib/exe/fetch.php?media=user:1542996:apoo_tads:diagrama_de_pacotes.pdf)
[Diagrama de pacotes](http://sgvclin.altervista.org/rea-uml/pop/pop-5/popup-texto5.html)

**Comment by edsondearaujo** [comment]
Subi uma primeira versão. Sei que precisamos detalhar mais.
v0.1.0

**Comment by edsondearaujo** [comment]
[v0.1.1](https://github.com/fga-eps-mds/2020-1-Ziguen/blob/docs/docs/diagramas/diagrama_pacotes_0.1.1.jpg)
