### ISSUE TITLE
BUG(Request Back-end)

### ISSUE THREAD

**Issue by Giuulob89** [fga-eps-mds/2020-1-Ziguen#94]
| Nome | Assunto| Título| Label | Assignees |
|------|------|------|------|-----|
| Request |  Bug no request| Bug| Bug/back-end | @Giuulob89 @francisco1code | 

## Descrição
Foi encontrado um bug na hora em que o front faz um request ao back

## Tarefa 

Resolver e descrever a solução

**Comment by Giuulob89** [comment]
@francisco1code issue criada!!

**Comment by francisco1code** [comment]
Resposta a **Tarefa**: estava acontecendo o bug por causa de permissões cors, então foi resolvido com a configuração do CORS.
