### ISSUE TITLE
Issue template feature_request

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#96]
| nome | atividade | labels | assignees |
|---------------|-----------------|-----------------|-------------|
|  Issue template feature_request | Alterar template | bug, documentation, invalid, pull_request, settings, work in progress  |  @edsondearaujo , @francisco1code    | 

## Descrição
Alterar template feature_request, incluir critério de aceitação.
   
## Tarefa 
   - [x] levantar pesquisa sobre arquivos na pasta .github.
   - [x] Estudar a pesquisa que foi realizada.
   - [x] Gerar automaticamente o template ao criar nova issue feature_request.
   - [x] Documentar na issue, o caminho percorrido para a realização da atividade. 

## Critério de aceitação
- [x] Checkbox das tarefas, preenchidos.
- [x] A solução deve funcionar corretamente.
- [x] Pelo menos dois membros do grupo devem verificar a atividade.

**Comment by edsondearaujo** [comment]
### Referências:
- [GitHub Docs](https://docs.github.com/pt/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
- [Lappis/tais](https://github.com/lappis-unb/tais/tree/master/.github/ISSUE_TEMPLATE)

**Comment by edsondearaujo** [comment]
Depois de bater muita cabeça, entendi como funciona esses templates e compreendi cada modelo.
o repositório do projeto [tais](https://github.com/lappis-unb/tais/tree/master/.github/ISSUE_TEMPLATE) é uma boa referência.

**Comment by francisco1code** [comment]
Funcionando certinho patrão!
